# Generated by Django 5.2.8 on 2025-11-18 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0004_tokenusage_notified_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenusage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chatbot_app.chatsession",
            ),
        ),
    ]
