# Generated by Django 5.2.8 on 2025-11-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0005_tokenusage_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenusage",
            name="anon_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
