# Generated by Django 5.1.6 on 2025-11-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0006_tokenusage_anon_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                ("id_adm", models.AutoField(primary_key=True, serialize=False)),
                ("correo_adm", models.CharField(max_length=100)),
                ("nombre_adm", models.CharField(max_length=50)),
                ("apellidop_adm", models.CharField(max_length=50)),
                ("apellidom_adm", models.CharField(max_length=50)),
                ("tel_adm", models.CharField(max_length=20)),
                ("pass_adm", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "administrador",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id_emp",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("RFC_emp", models.CharField(max_length=13)),
                ("nombre_emp", models.CharField(max_length=50)),
                ("logotipo_emp", models.CharField(max_length=255)),
                ("sitioweb_emp", models.CharField(max_length=255)),
                ("codigoPostal_emp", models.CharField(max_length=10)),
                ("estado_emp", models.CharField(max_length=100)),
                ("url_cs_emp", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "empresa",
                "managed": False,
            },
        ),
    ]
