# Generated by Django 5.1.6 on 2025-11-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0007_administrador_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("mejorar_descripcion", "Mejorar descripción"),
                            ("analisis_cv", "Análisis CV"),
                            ("chat_general", "Chat general"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("model_name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("function", models.CharField(blank=True, max_length=64)),
                ("template", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_original", models.TextField()),
                (
                    "fuente",
                    models.CharField(
                        choices=[("manual", "Manual"), ("sap", "SAP SSFF")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("publicado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_adm",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chatbot_app.administrador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobDescriptionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_mejorado", models.TextField()),
                ("salida_estructurada", models.JSONField(blank=True, null=True)),
                ("prompt_usado", models.TextField()),
                ("modelo_usado", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("memory_tokens", models.PositiveIntegerField(default=0)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_adm",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chatbot_app.administrador",
                    ),
                ),
                (
                    "job_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="chatbot_app.jobdescription",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chatbot_app.prompttemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chatbot_app.jobdescriptionrevision",
            ),
        ),
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_app.jobdescriptionrevision",
                    ),
                ),
            ],
        ),
    ]
