# Generated by Django 5.1.6 on 2025-11-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0008_aimodelconfig_prompttemplate_jobdescription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuestoSAP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_requisicion", models.IntegerField(unique=True)),
                ("categoria", models.CharField(max_length=255)),
                ("titulo", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("ubicacion", models.CharField(max_length=255)),
                ("fecha_importacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
