# Generated by Django 5.1.6 on 2025-11-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0009_puestosap"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeSAP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("url", models.URLField(unique=True)),
                ("fecha_configuracion", models.DateTimeField(auto_now_add=True)),
                ("ultima_descarga", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
