# Generated by Django 5.1.6 on 2025-11-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0010_informesap"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                ("id_candidate", models.AutoField(primary_key=True, serialize=False)),
                ("correo_candidate", models.CharField(max_length=50)),
                ("nombre_candidate", models.CharField(max_length=45)),
                ("apellidop_candidate", models.CharField(max_length=50)),
                ("apellidom_candidate", models.CharField(max_length=50)),
                ("tel_candidate", models.CharField(max_length=20)),
                ("CV_candidate", models.CharField(max_length=255)),
                ("CV_id_onedrive", models.CharField(max_length=100)),
                (
                    "token_verificacion",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("token_expira", models.DateTimeField(blank=True, null=True)),
                ("token_validado", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "candidato",
                "managed": False,
            },
        ),
    ]
