# Generated by Django 5.1.6 on 2025-11-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0011_candidato"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparacionCVPuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_puesto", models.CharField(max_length=255)),
                ("resultado", models.TextField()),
                ("score", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparaciones",
                        to="chatbot_app.candidato",
                    ),
                ),
            ],
        ),
    ]
