# Generated by Django 5.1.6 on 2025-11-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0012_comparacioncvpuesto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_id", models.CharField(max_length=50, unique=True)),
                ("descripcion_original", models.TextField()),
                ("descripcion_mejorada", models.TextField(blank=True, null=True)),
                ("fecha_mejora", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
